"""Added DM conversation tables

Revision ID: f56b6b4dc564
Revises: e7a92dc229f3
Create Date: 2026-05-13 23:15:02.042719

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "f56b6b4dc564"
down_revision = "e7a92dc229f3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "direct_conversations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("organisation_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["organisation_id"],
            ["organisations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "direct_conversation_members",
        sa.Column("direct_conversation_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["direct_conversation_id"],
            ["direct_conversations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("direct_conversation_id", "user_id"),
    )
    with op.batch_alter_table("messages", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("direct_conversation_id", sa.Integer(), nullable=True)
        )
        batch_op.alter_column(
            "channel_id",
            existing_type=sa.INTEGER(),
            nullable=True,
        )
        batch_op.create_foreign_key(
            "fk_messages_direct_conversation_id_direct_conversations",
            "direct_conversations",
            ["direct_conversation_id"],
            ["id"],
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("messages", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.alter_column("channel_id", existing_type=sa.INTEGER(), nullable=False)
        batch_op.drop_column("direct_conversation_id")

    op.drop_table("direct_conversation_members")
    op.drop_table("direct_conversations")
    # ### end Alembic commands ###
